// SERÁ MELHOR GUARDAR A LINGUAGEM COMO ESTADO NO APP OU COMO CONTEXTO ?
// NO MOMENTO ATUAL ESTÁ SENDO SALVO COMO ESTADO POIS SÓ ESTÁ SENDO ACESSADO EM FILHOS DIRETOS DO APP 

export const STRINGS = {
    'pt-BR': {
        'NO_DESCRIPTION': 'Sem descrição em português',
        'FORM_TITLE': 'Pesquisa TMDB',
        'FORM_SEARCHBAR': 'Termo de pesquisa',
        'FORM_SEARCHBTN': 'Pesquisar',
        'FORM_CATEGORY': 'Categoria',
        'FORM_CATEGORY_ALL': 'Todas',
        'FORM_CATEGORY_MOVIE': 'Filmes',
        'FORM_CATEGORY_TV': 'Séries',
        'FORM_CATEGORY_PERSON': 'Pessoas',
        'FORM_INCLUDE_NSFW': 'Incluir conteúdo adulto',
        'PAGE_CURRENT': 'Página CURRENT/TOTAL',
        'PAGE_RESULTS': 'Exibindo MIN-MAX de TOTAL resultados',
        'MONTHS': [
            'Janeiro',
            'Fevereiro',
            'Março',
            'Abril',
            'Maio',
            'Junho',
            'Julho',
            'Agosto',
            'Setembro',
            'Outubro',
            'Novembro',
            'Dezembro'
        ],
        'ATTRIBUTION': 'Desenvolvido com',
        'DETAILS_VOTE_AVG':'Média de Votos',
        'DETAILS_KNOWN_FOR': 'Conhecido por',
        'DETAILS_WATCHPROV': 'Onde assistir',
        'DETAILS_OVERVIEW': 'Sinopse',
        'DETAILS_STATUS': 'Situação',
        'DETAILS_BUDGET': 'Orçamento',
        'DETAILS_REVENUE': 'Rendimento',
        'DETAILS_NEXT_AIR': 'Próxima Exibição',
        'DETAILS_LAST_AIR': 'Ultima Exibição',
        'DETAILS_BIOGRAPHY': 'Biografia',
        'DETAILS_PLACEOFBIRTH': 'Local de Nascimento',
        'DETAILS_BIRTHDAY': 'Aniversário',
        'DETAILS_DEATHDAY': 'Dia da Morte'
    }, 'en-US': {
        'NO_DESCRIPTION': 'No english description',
        'FORM_TITLE': 'TMDB Search',
        'FORM_SEARCHBAR': 'Search term',
        'FORM_SEARCHBTN': 'Search',
        'FORM_CATEGORY': 'Category',
        'FORM_CATEGORY_ALL': 'All',
        'FORM_CATEGORY_MOVIE': 'Movies',
        'FORM_CATEGORY_TV': 'TV Shows',
        'FORM_CATEGORY_PERSON': 'Person',
        'FORM_INCLUDE_NSFW': 'Include NSFW content',
        'PAGE_CURRENT': 'Page CURRENT/TOTAL',
        'PAGE_RESULTS': 'Showing MIN-MAX out of TOTAL results',
        'MONTHS': [
            'January',
            'February',
            'March',
            'April',
            'May',
            'June',
            'July',
            'August',
            'September',
            'October',
            'November',
            'December'
        ],
        'ATTRIBUTION': 'Powered by',
        'DETAILS_VOTE_AVG': 'Vote Average',
        'DETAILS_KNOWN_FOR': 'Known for',
        'DETAILS_WATCHPROV': 'Watch Providers', 
        'DETAILS_OVERVIEW': 'Overview',
        'DETAILS_STATUS': 'Status',
        'DETAILS_BUDGET': 'Budget',
        'DETAILS_REVENUE': 'Revenue',
        'DETAILS_NEXT_AIR': 'Next Air Date',
        'DETAILS_LAST_AIR': 'Last Air Date',
        'DETAILS_BIOGRAPHY': 'Biography',
        'DETAILS_PLACEOFBIRTH': 'Place of Birth',
        'DETAILS_BIRTHDAY': 'Birthday',
        'DETAILS_DEATHDAY': 'Deathday'
    }
}